language: php
php:
  - 7.4
services:
  - mysql
env:
  global:
    - APP_ENV=testing
    - DB_USERNAME=travis
    - DB_PASSWORD=
before_script:
  - echo 'APP_KEY=SomeRandomString >> .env'
  - mysql -e 'create database lycee_overture_testing;'
  - composer self-update
  - composer install --no-interaction
  - bin/migrate-tests.sh
script: vendor/bin/phpunit
