#!/usr/bin/env sh

# This is so we can get the commit into the build log of a Dangerfile runner
# These come from https://docs.docker.com/docker-cloud/builds/advanced/

# For debugging all env vars
# printenv

docker build --build-arg=GIT_SHA1=$(git rev-parse HEAD) -t $IMAGE_NAME .
